name: Checks
on: [ pull_request, workflow_dispatch  ]
jobs:
  changed-files:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      ubuntu-files: ${{ steps.changes.outputs.ubuntu-files}}
      debian-files: ${{ steps.changes.outputs.debian-files}}
      centos-files: ${{ steps.changes.outputs.centos-files}}
      rhel-files: ${{ steps.changes.outputs.rhel-files}}
    steps:
      # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          git fetch origin "+refs/heads/${{github.base_ref}}:refs/remote/origin/${{github.head_ref}}"
          export UBUNTU_FILES="$(git diff --diff-filter=d --name-only origin/"${{github.base_ref}}" -- | grep ubuntu | base64 -w 0)"
          export DEBIAN_FILES="$(git diff --diff-filter=d --name-only origin/"${{github.base_ref}}" -- | grep debian | base64 -w 0)"
          export CENTOS_FILES="$(git diff --diff-filter=d --name-only origin/"${{github.base_ref}}" -- | grep centos | base64 -w 0)"
          export RHEL_FILES="$(git diff --diff-filter=d --name-only origin/"${{github.base_ref}}" -- | grep rhel | base64 -w 0)"
          echo "::set-output name=ubuntu-files::$(echo "$UBUNTU_FILES")"
          echo "::set-output name=debian-files::$(echo "$DEBIAN_FILES")"
          echo "::set-output name=centos-files::$(echo "$CENTOS_FILES")"
          echo "::set-output name=rhel-files::$(echo "$RHEL_FILES")"

  ubuntu-checks:
    name: Run modified scripts to test for errors on Ubuntu
    runs-on: ubuntu-latest
    container: 'ubuntu:latest'
    needs: changed-files
    if: ${{needs.changed-files.outputs.ubuntu-files}}
    steps:
      - uses: actions/checkout@v1
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - name: echo changed files
        run: |
          FILES=$(echo ${{needs.changed-files.outputs.ubuntu-files}} | base64 -d)
          for file in $FILES
          do
            echo "$file"
          done

  centos-checks:
    name: Run modified scripts to test for errors on CentOS
    runs-on: ubuntu-latest
    container: 'centos:latest'
    needs: changed-files
    if: ${{needs.changed-files.outputs.centos-files}}
    steps:
      - uses: actions/checkout@v1
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - name: echo changed files
        run: |
          FILES=$(echo ${{needs.changed-files.outputs.centos-files}} | base64 -d)
          for file in $FILES
          do
            echo "$file"
          done

  debian-checks:
    name: Run modified scripts to test for errors on Debian
    runs-on: ubuntu-latest
    container: 'debian:latest'
    needs: changed-files
    if: ${{needs.changed-files.outputs.debian-files}}
    steps:
      - uses: actions/checkout@v1
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - name: echo changed files
        run: |
          FILES=$(echo ${{needs.changed-files.outputs.debian-files}} | base64 -d)
          for file in $FILES
          do
            echo "$file"
          done

  rhel-checks:
    name: Run modified scripts to test for errors on RHEL
    runs-on: ubuntu-latest
    container: 'richxsl/rhel7:latest'
    needs: changed-files
    if: ${{needs.changed-files.outputs.rhel-files}}
    steps:
      - uses: actions/checkout@v1
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - name: echo changed files
        run: |
          FILES=$(echo ${{needs.changed-files.outputs.rhel-files}} | base64 -d)
          for file in $FILES
          do
            echo "$file"
          done
